### ISSUE TITLE
can it be used for dvb-c? cable tv for EPG and boque the channels?

### ISSUE THREAD

**Issue by sachin0606** [gfto/dvblast#16]
can it be used for dvb-c? cable tv for EPG and boque the channels?

**Comment by gfto** [comment]
Yes, dvblast works just fine with DVB-C, no idea what you mean in the second question.

**Comment by sachin0606** [comment]
second question is - can we generate PSI/Si means NIT table and EIT table from this

**Comment by gfto** [comment]
No, dvblast can not generate such tables. Use something like mptsd for that.
