### ISSUE TITLE
Suddenly DVBlast stopped working - does not bring out any stream

### ISSUE THREAD

**Issue by Tester2020-ik** [gfto/dvblast#24]
dvblast  -f 485028615 -a 0 --delsys ATSC -v 6 -c adapter0.conf
DVBlast 3.4 (release)
warning: restarting
debug: compiled with DVB API version 5.11
debug: using DVB API version 5.11
debug: Frontend "TurboSight TBS 6704(Quad ATSC/QAMB)" supports:
debug:  frequency min: 44000000, max: 1002000000, stepsize: 62500, tolerance: 0
debug:  symbolrate min: 0, max: 0, tolerance: 0
debug:  capabilities:
debug:   INVERSION_AUTO
debug:   FEC_AUTO
debug:   QAM_64
debug:   QAM_256
debug:   QAM_AUTO
debug:   8VSB
debug:  delivery systems:
debug:   ATSC
debug:   DVBC_ANNEX_B
debug: tuning ATSC frontend to f=485028615 inversion=-1 modulation=qam_auto
warning: failed opening CAM device /dev/dvb/adapter0/ca0 (No such file or directory)
debug: setting filter on PID 0
debug: setting filter on PID 16
debug: setting filter on PID 17
debug: setting filter on PID 18
debug: setting filter on PID 19
debug: setting filter on PID 20
debug: conf: 127.0.0.1:1001 config=0x1 sid=1 pids[0]
debug: change sid tsid 

..... < no output until i press CTRL-C>
^Cinfo: Shutdown was requested.
debug: removing 127.0.0.1:1001

**Comment by gfto** [comment]
Send the report to dvblast mailing list. Possible problems that you are seeing:
-  debug: Frontend "TurboSight TBS 6704(Quad ATSC/QAMB)" supports - This DVB card does not have drivers in upstream Linux, this means that the drivers are dodgy
- The fact that you are not getting anything quite possbily menas that the tunning parameters are not correct and you should check them.
