### ISSUE TITLE
Empty PAT is output 

### ISSUE THREAD

**Issue by przemo1983** [gfto/dvblast#8]
I am using DVBlast release 2.2.

In config file I have following line:
239.8.1.4:2112@192.168.226.55/udp	1 	0 	1077,3324,7088
So I want to output only PIDs: 1077,3324,7088, nothing more.
I run the DVBlast with following command:
./dvblast -D 239.0.0.3:2111/udp/ifaddr=10.8.8.1 -c config.cfg -l &
Unfortunately I got on output the empty PAT table (without any entries in program loop)

Is it possible not to output any PAT table? Is it known issue, or I am doing something wrong?

**Comment by gfto** [comment]
Report the issue to dvblast mailing list. We don't do development using github.
