### ISSUE TITLE
./dvblast: error while loading shared libraries: libev.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by on4bhm** [gfto/dvblast#9]
i'm trying to run dvblast on ubuntu 14.04 lts.
i get this error.
in /usr/local/lib there is a file libev.so.4

can you help?

**Comment by kunajinda2012** [comment]
https://lonesysadmin.net/2013/02/22/error-while-loading-shared-libraries-cannot-open-shared-object-file/
